[config]
version_check = false

[templates.btop]
input_path = "/home/max/.config/matugen/templates/btop.theme"
output_path = "/home/max/.config/btop/themes/matugen.theme"
post_hook = "pkill -SIGUSR2 btop"

[templates.zen]
input_path = "/home/max/.config/matugen/templates/userChrome.css"
output_path = "/home/max/.zen/davnng42.Default (release)/chrome/userChrome.css"

[templates.zen1]
input_path = "/home/max/.config/matugen/templates/userContent.css"
output_path = "/home/max/.zen/davnng42.Default (release)/chrome/userContent.css"

[templates.zen2]
input_path = "/home/max/.config/matugen/templates/zen-logo-mocha.svg"
output_path = "/home/max/.zen/davnng42.Default (release)/chrome/zen-mocha.svg"

[templates.niri]
input_path = "/home/max/.config/matugen/templates/niri-colors.kdl"
output_path = "/home/max/.config/niri/colors.kdl"

[templates.foot]
input_path = "/home/max/.config/matugen/templates/foot-colors-start.ini"
output_path = "/home/max/.config/foot/foot-colors.ini"
post_hook = "nohup ./foot-colors.sh \"{{colors.primary.default.hex}}\" &"

[templates.nvim]
input_path = "/home/max/.config/matugen/templates/nvim-colors.lua"
output_path = "/home/max/.config/nvim/colors/base46-matugen.lua"

# [templates.ratty]
# input_path = "/home/max/.config/matugen/templates/ratty.toml"
# output_path = "/home/max/.config/ratty/ratty.toml"
# 
# [templates.wezterm]
# input_path = "/home/max/.config/matugen/templates/wezterm-theme.toml"
# output_path = "/home/max/.config/wezterm/colors/wezterm-theme.toml"
# post_hook = "nohup ./wezterm-theme.sh \"{{colors.primary.default.hex}}\" &"
