#[config.wallpaper]
#command = "swww"
#arguments = ["img", "--transition-type", "center"]
#set = false

[config]

version_check = false

#[templates.kitty]
#input_path = "/home/max/.config/matugen/templates/kitty-colors.conf"
#output_path = "/home/max/.config/kitty/themes/your-theme.conf"
#post_hook = "kitty +kitten themes --reload-in=all your-theme"

[templates.btop]
input_path = "/home/max/.config/matugen/templates/btop.theme"
output_path = "/home/max/.config/btop/themes/matugen.theme"
post_hook = "pkill -SIGUSR2 btop"

#[templates.vesktop]
#input_path = "/home/max/.config/matugen/templates/midnight-discord.css"
#output_path = "/home/max/.config/vesktop/themes/midnight.theme.css"

#[templates.nvim]
#input_path = "/home/max/.config/matugen/templates/nvim-colors.lua"
#output_path = "/home/max/.config/nvim/generated.lua"
#post_hook = "pkill -SIGUSR1 nvim"

[templates.zen]
input_path = "/home/max/.config/matugen/templates/userChrome.css"
output_path = "/home/max/.zen/davnng42.Default (release)/chrome/userChrome.css"

[templates.zen1]
input_path = "/home/max/.config/matugen/templates/userContent.css"
output_path = "/home/max/.zen/davnng42.Default (release)/chrome/userContent.css"

[templates.zen2]
input_path = "/home/max/.config/matugen/templates/zen-logo-mocha.svg"
output_path = "/home/max/.zen/davnng42.Default (release)/chrome/zen-mocha.svg"

[templates.niri]
input_path = "/home/max/.config/matugen/templates/colors.kdl"
output_path = "/home/max/dotfiles/niri/.config/niri/colors.kdl"

[templates.vicinae]
input_path = "/home/max/.config/matugen/templates/vicinae.toml"
output_path = "~/.local/share/vicinae/themes/matugen.toml"
post_hook = "vicinae theme set matugen"

[templates.rofi]
input_path = "/home/max/.config/matugen/templates/rofi-colors.rasi"
output_path = "/home/max/.config/rofi/applets/shared/colors.rasi"

[templates.lualine]
input_path = "/home/max/.config/matugen/templates/dank-lualine.lua"
output_path = "/home/max/.config/nvim/lua/plugins/dank-lualine.lua"
