[config]
#[config.wallpaper]
#command = ""
#arguments = ["img", "--transition-type", "center"]
#set = false

#[templates.waybar]
#input_path = "/home/max/.config/matugen/templates/colors.css"
#output_path = "/home/max/.config/waybar/colors.css"
#post_hook = "pkill -SIGUSR2 waybar"

[templates.hyprland]
input_path = "/home/max/.config/matugen/templates/hyprland-colors.conf"
output_path = "/home/max/.config/hypr/colors.conf"

#[templates.hyprlock]
#input_path = "/home/max/.config/matugen/templates/hyprland-colors.conf"
#output_path = "/home/max/.config/hypr/colors.conf"

[templates.kitty]
input_path = "/home/max/.config/matugen/templates/kitty-colors.conf"
output_path = "/home/max/.config/kitty/themes/your-theme.conf"
post_hook = "kitty +kitten themes --reload-in=all your-theme"

#[templates.rofi]
#input_path = "/home/max/.config/matugen/templates/rofi-colors.rasi"
#output_path = "/home/max/.config/rofi/colors.rasi"

#[templates.mako]
#input_path = "/home/max/.config/matugen/templates/mako"
#output_path = "/home/max/.config/mako/mako-colors"
#post_hook = "makoctl reload"

[templates.btop]
input_path = "/home/max/.config/matugen/templates/btop.theme"
output_path = "/home/max/.config/btop/themes/matugen.theme"
post_hook = "killall -SIGUSR2 btop"

[templates.yazi]
input_path = "/home/max/.config/matugen/templates/yazi-theme.toml"
output_path = "/home/max/.config/yazi/theme.toml"
post_hook = "killall -SIGUSR2 yazi"

[templates.vesktop]
input_path = "/home/max/.config/matugen/templates/midnight-discord.css"
output_path = "/home/max/.config/vesktop/themes/midnight.theme.css"

[templates.pywalfox]
input_path = "/home/max/.config/matugen/templates/pywalfox-colors.json"
output_path = "/home/max/.cache/wal/colors.json"
post_hook = "pywalfox update"

[templates.cava]
input_path = "/home/max/.config/matugen/templates/cava-colors.ini"
output_path = "/home/max/.config/cava/themes/your-theme"
post_hook = "pkill -USR2 cava"

[templates.nvim]
input_path = "/home/max/.config/matugen/templates/nvim-colors.lua"
output_path = "/home/max/.config/nvim/generated.lua"
post_hook = "pkill -SIGUSR1 nvim"

[templates.clipse]
input_path = "/home/max/.config/matugen/templates/clipse-theme.json"
output_path = "/home/max/.config/clipse/custom_theme.json"

[templates.ff]
input_path = "/home/max/.config/matugen/templates/ff-colors.jsonc"
output_path = "/home/max/.config/fastfetch/config.jsonc"

[templates.zen]
input_path = "/home/max/.config/matugen/templates/userChrome.css"
output_path = "/home/max/.zen/u2exuqh8.Default (release)/chrome/userChrome.css"

[templates.zen1]
input_path = "/home/max/.config/matugen/templates/userContent.css"
output_path = "/home/max/.zen/u2exuqh8.Default (release)/chrome/userContent.css"

[templates.zen2]
input_path = "/home/max/.config/matugen/templates/zen-logo-mocha.svg"
output_path = "/home/max/.zen/u2exuqh8.Default (release)/chrome/zen-mocha.svg"

[templates.spicetify]
#pre_hook = "spicetify watch -s &"
input_path = "/home/max/.config/matugen/templates/spicetify-colors.ini"
output_path = "/home/max/.config/spicetify/Themes/text/color.ini"

[templates.niri]
input_path = "/home/max/.config/matugen/templates/colors.kdl"
output_path = "/home/max/dotfiles/niri/.config/niri/colors.kdl"
