[font]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
size = 16

[cursor.model]
path = "CairoSpinyMouse.obj"
scale_factor = 6.0
brightness = 0.5
x_offset = 0.5
plane_offset = 18.0
visible = true

[cursor.animation]
spin_speed = 1.4
bob_speed = 2.2
bob_amplitude = 0.08

[bindings]
keys = [
  { key = "C", with = "Control | shift", action = "Copy" },
  { key = "V", with = "Control | shift", action = "Paste" },
  { key = "Equal", with = "Control", action = "IncreaseFontSize" },
  { key = "Minus", with = "Control", action = "DecreaseFontSize" },
  { key = "Digit0", with = "Control | shift", action = "ResetFontSize" },
  { key = "Enter", with = "Control | shift", action = "Toggle3DMode" },
  { key = "M", with = "Control | shift", action = "ToggleMobiusMode" },
  { key = "Up", with = "Control | shift", action = "IncreaseWarp" },
  { key = "Down", with = "Control | shift", action = "DecreaseWarp" },
]

[theme]
foreground = "#dee4df"
background = "#0f1512"
cursor = "#dee4df"

[theme.normal]
black =   "#070305"
red =     "#141811"
green =   "#212d1e"
yellow =  "#2f412a"
blue =    "#3c5636"
magenta = "#496b42"
cyan =    "#56804e"
white =   "#63955a"

[theme.bright]
black =   "#108b57"
red =     "#136143"
green =   "#639459"
yellow =  "#0d4735"
blue =    "#08372a"
magenta = "#062f25"
cyan =    "#062c23"
white =   "#ffffff"
