[font]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
size = 16

[cursor.model]
path = "CairoSpinyMouse.obj"
scale_factor = 6.0
brightness = 0.5
x_offset = 0.5
plane_offset = 18.0
visible = true

[cursor.animation]
spin_speed = 1.4
bob_speed = 2.2
bob_amplitude = 0.08

[bindings]
keys = [
  { key = "C", with = "Control | shift", action = "Copy" },
  { key = "V", with = "Control | shift", action = "Paste" },
  { key = "Equal", with = "Control", action = "IncreaseFontSize" },
  { key = "Minus", with = "Control", action = "DecreaseFontSize" },
  { key = "Digit0", with = "Control | shift", action = "ResetFontSize" },
  { key = "Enter", with = "Control | shift", action = "Toggle3DMode" },
  { key = "M", with = "Control | shift", action = "ToggleMobiusMode" },
  { key = "Up", with = "Control | shift", action = "IncreaseWarp" },
  { key = "Down", with = "Control | shift", action = "DecreaseWarp" },
]

[theme]
foreground = "#f0dfd7"
background = "#1a120d"
cursor = "#f0dfd7"

[theme.normal]
black =   "#191511"
red =     "#2e2922"
green =   "#423c34"
yellow =  "#565046"
blue =    "#6a6358"
magenta = "#7f7769"
cyan =    "#938b7b"
white =   "#a79e8d"

[theme.bright]
black =   "#c55615"
red =     "#c87a28"
green =   "#a86229"
yellow =  "#903f21"
blue =    "#c18a5b"
magenta = "#9a7052"
cyan =    "#735741"
white =   "#ffffff"
