[font]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
size = 16

[cursor.model]
path = "CairoSpinyMouse.obj"
scale_factor = 6.0
brightness = 0.5
x_offset = 0.5
plane_offset = 18.0
visible = true

[cursor.animation]
spin_speed = 1.4
bob_speed = 2.2
bob_amplitude = 0.08

[bindings]
keys = [
  { key = "C", with = "Control | shift", action = "Copy" },
  { key = "V", with = "Control | shift", action = "Paste" },
  { key = "Equal", with = "Control", action = "IncreaseFontSize" },
  { key = "Minus", with = "Control", action = "DecreaseFontSize" },
  { key = "Digit0", with = "Control | shift", action = "ResetFontSize" },
  { key = "Enter", with = "Control | shift", action = "Toggle3DMode" },
  { key = "M", with = "Control | shift", action = "ToggleMobiusMode" },
  { key = "Up", with = "Control | shift", action = "IncreaseWarp" },
  { key = "Down", with = "Control | shift", action = "DecreaseWarp" },
]

[theme]
foreground = "{{colors.on_surface.default.hex}}"
background = "{{colors.background.default.hex}}"
cursor = "{{colors.on_surface.default.hex}}"

[theme.normal]
black =   "{{base16.base00.default.hex}}"
red =     "{{base16.base01.default.hex}}"
green =   "{{base16.base02.default.hex}}"
yellow =  "{{base16.base03.default.hex}}"
blue =    "{{base16.base04.default.hex}}"
magenta = "{{base16.base05.default.hex}}"
cyan =    "{{base16.base06.default.hex}}"
white =   "{{base16.base07.default.hex}}"

[theme.bright]
black =   "{{base16.base08.default.hex}}"
red =     "{{base16.base09.default.hex}}"
green =   "{{base16.base0a.default.hex}}"
yellow =  "{{base16.base0b.default.hex}}"
blue =    "{{base16.base0c.default.hex}}"
magenta = "{{base16.base0d.default.hex}}"
cyan =    "{{base16.base0e.default.hex}}"
white =   "#ffffff"
