"$schema" = 'https://starship.rs/config-schema.json'

format = """
\u256d\u2574\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_metrics\
$git_state\
$cmd_duration\
$line_break\
$python\
\u2570\u2500\
$character"""

add_newline = false

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
detect_extensions = []
detect_files = []

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_status]
ahead = "⇡${count}"
behind = "⇣{count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[git_metrics]
disabled = false
