[main]
pad=18x18x0x0
#letter-spacing=0
#line-height=12
box-drawings-uses-font-glyphs=no
gamma-correct-blending=yes
#dpi-aware=yes
font=Maple Mono NF:size=11.5:weight=140:antialias=true:autohint=false:hinting=false:rgba=none
include=/home/max/.config/foot/foot-colors.ini

[scrollback]
# Scrollback
lines=3000

[cursor]
style=block
#blink=yes

[mouse]
#hide-when-typing=yes

[tweak]
box-drawing-base-thickness=0.07

[colors-dark]
cursor=111111 dcdccc
