[main]
pad=18x18x0x0
#letter-spacing=0
#line-height=12
box-drawings-uses-font-glyphs=no
#dpi-aware=yes
font=JetBrainsMono Nerd Font Mono:size=11:weight=183:antialias=true:autohint=false:hintstyle=hintslight:rgba=none
include=/home/max/.config/foot/dank-colors.ini

[scrollback]
# Scrollback
lines=3000

[cursor]
style=block
#blink=yes

[mouse]
#hide-when-typing=yes

[tweak]
box-drawing-base-thickness=0.07

[colors-dark]
cursor=111111 dcdccc
