# ~/.config/hypr/hyprland.conf
source = ./colors.conf
source = ./autostart.conf
source = ./binds.conf
source = ./input.conf
source = ./lookandfeel.conf
source = ./monitors.conf
source = ./programs.conf
source = ./variables.conf
source = ./windows.conf
source = ./animations.conf
#####################
### COLORS - MATUGEN ###
### Only valid Hyprland variables
#####################

general {
    # Window border colors
    col.active_border = $primary
    col.inactive_border = $background
}
