[colors]
background = '#161217'
foreground = '#e9e0e7'

cursor_bg = '#e9e0e7'
cursor_fg = '#161217'
cursor_border = '#cec3ce'

selection_bg = '#d3c0d8'
selection_fg = '#382c3e'
ansi = ['#1a1a1a', '#ff7289', '#7af599', '#ffdc72', '#d1a2e8', '#603c71', '#e1b7f5', '#faefff']
brights = ['#9b939f', '#ff9fae', '#a5ffbc', '#ffe8a5', '#edc8ff', '#f0d1ff', '#f5e1ff', '#fcf8ff']
