[colors]
background = '#0f1512'
foreground = '#dee4df'

cursor_bg = '#dee4df'
cursor_fg = '#0f1512'
cursor_border = '#bfc9c3'

selection_bg = '#b2ccc1'
selection_fg = '#1e352d'
ansi = ['#1a1a1a', '#f6996e', '#6bd66f', '#fff272', '#72cbab', '#20634b', '#88d6ba', '#d3e0db']
brights = ['#808b87', '#ffbd9f', '#a5ffa9', '#fff7a5', '#a2ebd1', '#bdffe7', '#d5ffef', '#f8fffc']
