[colors]
background = '#1a120d'
foreground = '#f0dfd7'

cursor_bg = '#f0dfd7'
cursor_fg = '#1a120d'
cursor_border = '#d7c2b8'

selection_bg = '#e5bfaa'
selection_fg = '#432b1c'
ansi = ['#1a1a1a', '#ff7872', '#96ff7f', '#ffe572', '#f29f6e', '#763813', '#ffb68b', '#fff5ef']
brights = ['#a59d99', '#ffa39f', '#b5ffa5', '#ffefa5', '#ffc09c', '#ffcbad', '#ffdeca', '#fffbf8']
