$mainMod = SUPER

bind = $mainMod, B, exec, zen
bind = $mainMod SHIFT, B, exec, kitty btop 
bind = $mainMod, D, killactive,
bind = $mainMod SHIFT, D, exit,
bind = $mainMod, E, exec, kitty yazi
bind = $mainMod, F, exec, kitty -e zsh -i -c "fastfetch; exec zsh"
bind = $mainMod, M, exec, spotify
bind = $mainMod, N, exec, kitty nvim
bind = $mainMod, O, exec, dms ipc call lock lock
bind = $mainMod SHIFT, O, exec, kitty obs
bind = $mainMod, P, exec, hyprpicker
bind = $mainMod, R, exec, dms kill; sleep 1; systemctl --user start dms
bind = $mainMod SHIFT, S, exec, hyprshot -o ~/screenshots -z -m region
bind = $mainMod, S, exec, dms ipc call night toggle
bind = $mainMod, T, togglefloating,
bind = $mainMod, V, exec, vesktop
bind = $mainMod SHIFT, W, exec, waypaper
bind = $mainMod, Return, exec, kitty
bind = $mainMod, SPACE, exec, dms ipc call spotlight open
bind = $mainMod, UP, togglesplit, # dwindle
bind = $mainMod, End, exec, dms ipc call mpris playPause
bind = $mainMod, Home, exec, dms ipc call mpris next
bind = $mainMod, Delete, exec, dms ipc call mpris previous

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod SHIFT, H, movewindow, l 
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
