
$image = /home/max/wall/redCloudCity.jpg
$background = rgba(1a110eff)

$image = /home/max/wall/redCloudCity.jpg
$error = rgba(ffb4abff)

$image = /home/max/wall/redCloudCity.jpg
$error_container = rgba(93000aff)

$image = /home/max/wall/redCloudCity.jpg
$inverse_on_surface = rgba(382e2aff)

$image = /home/max/wall/redCloudCity.jpg
$inverse_primary = rgba(8e4d2fff)

$image = /home/max/wall/redCloudCity.jpg
$inverse_surface = rgba(f1dfd9ff)

$image = /home/max/wall/redCloudCity.jpg
$on_background = rgba(f1dfd9ff)

$image = /home/max/wall/redCloudCity.jpg
$on_error = rgba(690005ff)

$image = /home/max/wall/redCloudCity.jpg
$on_error_container = rgba(ffdad6ff)

$image = /home/max/wall/redCloudCity.jpg
$on_primary = rgba(552106ff)

$image = /home/max/wall/redCloudCity.jpg
$on_primary_container = rgba(ffdbcdff)

$image = /home/max/wall/redCloudCity.jpg
$on_primary_fixed = rgba(360f00ff)

$image = /home/max/wall/redCloudCity.jpg
$on_primary_fixed_variant = rgba(71361aff)

$image = /home/max/wall/redCloudCity.jpg
$on_secondary = rgba(442a1fff)

$image = /home/max/wall/redCloudCity.jpg
$on_secondary_container = rgba(ffdbcdff)

$image = /home/max/wall/redCloudCity.jpg
$on_secondary_fixed = rgba(2c160cff)

$image = /home/max/wall/redCloudCity.jpg
$on_secondary_fixed_variant = rgba(5d4034ff)

$image = /home/max/wall/redCloudCity.jpg
$on_surface = rgba(f1dfd9ff)

$image = /home/max/wall/redCloudCity.jpg
$on_surface_variant = rgba(d8c2baff)

$image = /home/max/wall/redCloudCity.jpg
$on_tertiary = rgba(373106ff)

$image = /home/max/wall/redCloudCity.jpg
$on_tertiary_container = rgba(efe3a9ff)

$image = /home/max/wall/redCloudCity.jpg
$on_tertiary_fixed = rgba(201c00ff)

$image = /home/max/wall/redCloudCity.jpg
$on_tertiary_fixed_variant = rgba(4e471bff)

$image = /home/max/wall/redCloudCity.jpg
$outline = rgba(a08d85ff)

$image = /home/max/wall/redCloudCity.jpg
$outline_variant = rgba(53443eff)

$image = /home/max/wall/redCloudCity.jpg
$primary = rgba(ffb596ff)

$image = /home/max/wall/redCloudCity.jpg
$primary_container = rgba(71361aff)

$image = /home/max/wall/redCloudCity.jpg
$primary_fixed = rgba(ffdbcdff)

$image = /home/max/wall/redCloudCity.jpg
$primary_fixed_dim = rgba(ffb596ff)

$image = /home/max/wall/redCloudCity.jpg
$scrim = rgba(000000ff)

$image = /home/max/wall/redCloudCity.jpg
$secondary = rgba(e6beaeff)

$image = /home/max/wall/redCloudCity.jpg
$secondary_container = rgba(5d4034ff)

$image = /home/max/wall/redCloudCity.jpg
$secondary_fixed = rgba(ffdbcdff)

$image = /home/max/wall/redCloudCity.jpg
$secondary_fixed_dim = rgba(e6beaeff)

$image = /home/max/wall/redCloudCity.jpg
$shadow = rgba(000000ff)

$image = /home/max/wall/redCloudCity.jpg
$source_color = rgba(bf5d2eff)

$image = /home/max/wall/redCloudCity.jpg
$surface = rgba(1a110eff)

$image = /home/max/wall/redCloudCity.jpg
$surface_bright = rgba(423733ff)

$image = /home/max/wall/redCloudCity.jpg
$surface_container = rgba(271e1aff)

$image = /home/max/wall/redCloudCity.jpg
$surface_container_high = rgba(322824ff)

$image = /home/max/wall/redCloudCity.jpg
$surface_container_highest = rgba(3d322eff)

$image = /home/max/wall/redCloudCity.jpg
$surface_container_low = rgba(231a16ff)

$image = /home/max/wall/redCloudCity.jpg
$surface_container_lowest = rgba(140c09ff)

$image = /home/max/wall/redCloudCity.jpg
$surface_dim = rgba(1a110eff)

$image = /home/max/wall/redCloudCity.jpg
$surface_tint = rgba(ffb596ff)

$image = /home/max/wall/redCloudCity.jpg
$surface_variant = rgba(53443eff)

$image = /home/max/wall/redCloudCity.jpg
$tertiary = rgba(d2c78fff)

$image = /home/max/wall/redCloudCity.jpg
$tertiary_container = rgba(4e471bff)

$image = /home/max/wall/redCloudCity.jpg
$tertiary_fixed = rgba(efe3a9ff)

$image = /home/max/wall/redCloudCity.jpg
$tertiary_fixed_dim = rgba(d2c78fff)

