$font = JetBrainsMono NFM
general {
    hide_cursor = true
}
animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}
background {
    monitor =
    path = screenshot
    blur_passes = 2
}
input-field {
    monitor =
    size = 15%, 4%
    outline_thickness = 0
    inner_color = rgba(255, 255, 255, .075)

    outer_color = rgba(0,0,0,0)
    check_color = rgb(255,0,0)
    fail_color = rgb(255,0,0)

    font_color = rgb(255,255,255)
    fade_on_empty = false
    rounding = 30

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = **
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, 100
    halign = center
    valign = bottom
}
label {
  monitor = 
  text = $TIME
  font_size = 90
  font_family = $font
  position = 0, 0
  halign = center
  valign = center
}
