# : Manager [[[

[mgr]
cwd = { fg = "#f0dede" }

# Tab
tab_active = { fg = "#561d24", bg = "#ffb2b7", bold = true }
tab_inactive = { fg = "#ffdadb", bg = "#3b0810" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffaf4d", bg = "#ffaf4d" }
marker_cut = { fg = "#ffddb3", bg = "#ffddb3" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e7c08e", bg = "#e7c08e" }

# Count
count_copied = { fg = "#291800", bg = "#ffddb3" }
count_cut = { fg = "#291800", bg = "#ffddb3" }
count_selected = { fg = "#561d24", bg = "#e7c08e" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb2b7" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#561d24", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb2b7", fg = "#561d24", bold = true }
normal_alt  = { bg = "#524344", fg = "#d7c1c2" }

# Select mode
select_main = { bg = "#e6bdbe", fg = "#44292b", bold = true }
select_alt  = { bg = "#524344", fg = "#d7c1c2" }

# Unset mode
unset_main = { bg = "#e7c08e", fg = "#432c06", bold = true }
unset_alt  = { bg = "#524344", fg = "#d7c1c2" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb2b7", bg = "#413737" }
progress_error = { fg = "#ffb4ab", bg = "#413737" }

# Permissions
permissions_t = { fg = "#bc4e51" }
permissions_w = { fg = "#b57727" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff991a" }
permissions_s = { fg = "#ff4146" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb2b7" }
active = { fg = "#e7c08e", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb2b7" }
value = { fg = "#f0dede" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ffb2b7", bold = true, bg = "#1a1112" }
inactive = { fg = "#e6bdbe", bg = "#1a1112" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb2b7", bg = "#561d24" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb2b7" }
title = {}
hovered = { fg = "#ffddb3", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413737" }
cand = { fg = "#ffb2b7" }
rest = { fg = "#561d24" }
desc = { fg = "#f0dede" }
separator = " ▶ "
separator_style = { fg = "#f0dede" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f0dede" }
run = { fg = "#f0dede" }
footer = { fg = "#44292b", bg = "#e6bdbe" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e7c08e" }
title_warn = { fg = "#ffb2b7" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f0dede" },
    { name = "*/", fg = "#ffb2b7" },
]

# : ]]]
