# : Manager [[[

[mgr]
cwd = { fg = "#f0dedd" }

# Tab
tab_active = { fg = "#571d1e", bg = "#ffb3b0", bold = true }
tab_inactive = { fg = "#ffdad8", bg = "#3b080b" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffb644", bg = "#ffb644" }
marker_cut = { fg = "#ffdeaa", bg = "#ffdeaa" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e3c28c", bg = "#e3c28c" }

# Count
count_copied = { fg = "#271900", bg = "#ffdeaa" }
count_cut = { fg = "#271900", bg = "#ffdeaa" }
count_selected = { fg = "#571d1e", bg = "#e3c28c" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb3b0" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#571d1e", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb3b0", fg = "#571d1e", bold = true }
normal_alt  = { bg = "#534342", fg = "#d7c1c0" }

# Select mode
select_main = { bg = "#e7bdba", fg = "#442928", bold = true }
select_alt  = { bg = "#534342", fg = "#d7c1c0" }

# Unset mode
unset_main = { bg = "#e3c28c", fg = "#412d05", bold = true }
unset_alt  = { bg = "#534342", fg = "#d7c1c0" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb3b0", bg = "#423736" }
progress_error = { fg = "#ffb4ab", bg = "#423736" }

# Permissions
permissions_t = { fg = "#c05048" }
permissions_w = { fg = "#ac7b2a" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ffa311" }
permissions_s = { fg = "#ff493f" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb3b0" }
active = { fg = "#e3c28c", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb3b0" }
value = { fg = "#f0dedd" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ffb3b0", bold = true, bg = "#1a1111" }
inactive = { fg = "#e7bdba", bg = "#1a1111" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb3b0", bg = "#571d1e" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb3b0" }
title = {}
hovered = { fg = "#ffdeaa", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#423736" }
cand = { fg = "#ffb3b0" }
rest = { fg = "#571d1e" }
desc = { fg = "#f0dedd" }
separator = " ▶ "
separator_style = { fg = "#f0dedd" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f0dedd" }
run = { fg = "#f0dedd" }
footer = { fg = "#442928", bg = "#e7bdba" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e3c28c" }
title_warn = { fg = "#ffb3b0" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f0dedd" },
    { name = "*/", fg = "#ffb3b0" },
]

# : ]]]
