cursor                #e8e0e5
cursor_text_color     #151216
background            #151216
foreground            #e8e0e5
selection_foreground  #cec3ce
selection_background  #4b444d
url_color             #e7b4ff

color0 #151216
color1 #ffb4ab
color2 #f4b7b7
color3 #d3c0d8
color4 #e7b4ff
color5 #f4b7b7
color6 #d3c0d8
color7 #e8e0e5
color8 #978e98
color9 #ffb4ab
color10 #f4b7b7
color11 #d3c0d8
color12 #e7b4ff
color13 #f4b7b7
color14 #d3c0d8
color15 #e8e0e5
