cursor                #dee3e5
cursor_text_color     #0e1416
background            #0e1416
foreground            #dee3e5
selection_foreground  #bfc8cb
selection_background  #3f484b
url_color             #83d2e4

color0 #072236
color1 #1a4052
color2 #2e5e6f
color3 #417c8b
color4 #559aa8
color5 #68b8c4
color6 #7cd6e0
color7 #8ff4fd
color8 #1bbbe2
color9 #0486ab
color10 #06678d
color11 #014e7f
color12 #02577e
color13 #014674
color14 #8ff3fc
color15 #04486b
