cursor                #e9e0e7
cursor_text_color     #cec3ce

foreground            #e9e0e7
background            #161217
selection_foreground  #382c3e
selection_background  #d3c0d8
url_color             #e1b7f5

# black
color0 #161217
color8 #5c6370


# red
color1 #dc553f
color9 #e0705f

# green
color2  #6ed67a
color10 #86e08f

# yellow
color3  #d8db7b
color11 #e5e897

# blue
color4  #ae62d0
color12 #f1c4ff

# magenta
color5  #ab92b7
color13 #9464c0

# cyan
color6  #e1b7f5
color14 #9d64aa

# white
color7  #abb2bf
color15 #ffffff
