cursor #dee3e5
cursor_text_color #bfc8cb

foreground            #dee3e5
background            #0e1416
selection_foreground  #1c3439
selection_background  #b2cbd1
url_color             #83d2e4

color0   #0e1416
color1   #ff72a2
color2   #72e47d
color3   #fff572
color4   #6ac4d8
color5   #175a69
color6   #83d2e4
color7   #e1ecef
color8   #899294
color9   #ff9fbf
color10  #a5ffae
color11  #fff9a5
color12  #a0e9fa
color13  #b3f0ff
color14  #cef5ff
color15  #f8fdff
