cursor #e7e2d5
cursor_text_color #ccc6b5

foreground            #e7e2d5
background            #15130c
selection_foreground  #353117
selection_background  #cec7a2
url_color             #d5c871

color0   #15130c
color1   #e24a77
color2   #92d66e
color3   #dbb27b
color4   #9c8e2f
color5   #9f9763
color6   #d5c871
color7   #abb2bf
color8   #5c6370
color9   #e05f89
color10  #a5e086
color11  #e8c597
color12  #e3d689
color13  #8e753f
color14  #7d7d3f
color15  #ffffff
